kind: Deployment
metadata:
  name: hr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    
    spec:
      containers:
      - name: hr-app
        image: richitha23/hr-app:latest

        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/fitness-tracker"
        - name: PORT
          value: "5000"
        - name: HOST
          value: "0.0.0.0"
        - name: NODE_ENV
          value: "production"        
---
apiVersion: v1
kind: Service
metadata:
  name: hr-service
spec:
  selector:
    app: hr-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer